[2025-08-11 06:43:11] [INFO    ] discord.client: logging in using static token
[2025-08-11 06:43:13] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 09d8c6e7bc612a48892208b15bd0275b).
[2025-08-11 07:07:44] [WARNING ] discord.gateway: Shard ID None has stopped responding to the gateway. Closing and restarting.
[2025-08-11 07:07:46] [INFO    ] discord.gateway: Shard ID None session has been invalidated.
[2025-08-11 07:07:52] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 1b6796ceecd7d89e00d783eb8d03fa62).
[2025-08-11 07:07:55] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\PythonProject\.venv\Lib\site-packages\discord\client.py", line 481, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\user\PycharmProjects\PythonProject\main.py", line 340, in on_ready
    save_logs_periodically.start()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\user\PycharmProjects\PythonProject\.venv\Lib\site-packages\discord\ext\tasks\__init__.py", line 400, in start
    raise RuntimeError('Task is already launched and is not completed.')
RuntimeError: Task is already launched and is not completed.
